/*
 * Copyright 2023-2024 NXP
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Includes */

#include "fsl_fract_pll.h"
#include "fsl_fro.h"
#include "fsl_ccm.h"
#include "fsl_clock.h"
#include "fsl_power.h"
#include "fsl_src.h"
#include "fsl_device_registers.h"

/* Local Defines */

/* Local Types */

/* Local Functions */

static bool CLOCK_SourcePdIsOn(uint32_t sourceIdx);

/* Local Variables */

uint64_t g_clockExt1Rate = 0UL;

const pll_attr_t g_pllAttrs[CLOCK_NUM_PLL] =
{
    [CLOCK_PLL_SYS1].isFrac = true,
    [CLOCK_PLL_SYS1].numDFS = 3U,

    [CLOCK_PLL_AUDIO1].isFrac = true,
    [CLOCK_PLL_AUDIO1].numDFS = 0U,

    [CLOCK_PLL_AUDIO2].isFrac = true,
    [CLOCK_PLL_AUDIO2].numDFS = 0U,

    [CLOCK_PLL_VIDEO1].isFrac = true,
    [CLOCK_PLL_VIDEO1].numDFS = 0U,

    [CLOCK_PLL_ARM].isFrac = false,
    [CLOCK_PLL_ARM].numDFS = 4U,

    [CLOCK_PLL_DRAM].isFrac = true,
    [CLOCK_PLL_DRAM].numDFS = 0U,

    [CLOCK_PLL_HSIO].isFrac = true,
    [CLOCK_PLL_HSIO].numDFS = 0U,

    [CLOCK_PLL_LDB].isFrac = true,
    [CLOCK_PLL_LDB].numDFS = 0U,
};

static const uint8_t s_clockSourceNumInputs[CLOCK_NUM_SRC] =
{
    [CLOCK_SRC_SYSPLL1_PFD0_UNGATED] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD0] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD0_DIV2] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD1_UNGATED] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD1] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD1_DIV2] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD2_UNGATED] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD2] = 1U,
    [CLOCK_SRC_SYSPLL1_PFD2_DIV2] = 1U,
    [CLOCK_SRC_AUDIOPLL1] = 1U,
    [CLOCK_SRC_AUDIOPLL2] = 1U,
    [CLOCK_SRC_VIDEOPLL1] = 1U,
    [CLOCK_SRC_ARMPLL_PFD0_UNGATED] = 1U,
    [CLOCK_SRC_ARMPLL_PFD0] = 1U,
    [CLOCK_SRC_ARMPLL_PFD1_UNGATED] = 1U,
    [CLOCK_SRC_ARMPLL_PFD1] = 1U,
    [CLOCK_SRC_ARMPLL_PFD2_UNGATED] = 1U,
    [CLOCK_SRC_ARMPLL_PFD2] = 1U,
    [CLOCK_SRC_ARMPLL_PFD3_UNGATED] = 1U,
    [CLOCK_SRC_ARMPLL_PFD3] = 1U,
    [CLOCK_SRC_DRAMPLL] = 1U,
    [CLOCK_SRC_HSIOPLL] = 1U,
    [CLOCK_SRC_LDBPLL] = 1U
};

static const uint8_t s_clockSourceParent[CLOCK_NUM_SRC] =
{
    [CLOCK_SRC_SYSPLL1_PFD0_UNGATED] = CLOCK_SRC_SYSPLL1_VCO,
    [CLOCK_SRC_SYSPLL1_PFD0] = CLOCK_SRC_SYSPLL1_PFD0_UNGATED,
    [CLOCK_SRC_SYSPLL1_PFD0_DIV2] = CLOCK_SRC_SYSPLL1_PFD0_UNGATED,
    [CLOCK_SRC_SYSPLL1_PFD1_UNGATED] = CLOCK_SRC_SYSPLL1_VCO,
    [CLOCK_SRC_SYSPLL1_PFD1] = CLOCK_SRC_SYSPLL1_PFD1_UNGATED,
    [CLOCK_SRC_SYSPLL1_PFD1_DIV2] = CLOCK_SRC_SYSPLL1_PFD1_UNGATED,
    [CLOCK_SRC_SYSPLL1_PFD2_UNGATED] = CLOCK_SRC_SYSPLL1_VCO,
    [CLOCK_SRC_SYSPLL1_PFD2] = CLOCK_SRC_SYSPLL1_PFD2_UNGATED,
    [CLOCK_SRC_SYSPLL1_PFD2_DIV2] = CLOCK_SRC_SYSPLL1_PFD2_UNGATED,
    [CLOCK_SRC_AUDIOPLL1] = CLOCK_SRC_AUDIOPLL1_VCO,
    [CLOCK_SRC_AUDIOPLL2] = CLOCK_SRC_AUDIOPLL2_VCO,
    [CLOCK_SRC_VIDEOPLL1] = CLOCK_SRC_VIDEOPLL1_VCO,
    [CLOCK_SRC_ARMPLL_PFD0_UNGATED] = CLOCK_SRC_ARMPLL_VCO,
    [CLOCK_SRC_ARMPLL_PFD0] = CLOCK_SRC_ARMPLL_PFD0_UNGATED,
    [CLOCK_SRC_ARMPLL_PFD1_UNGATED] = CLOCK_SRC_ARMPLL_VCO,
    [CLOCK_SRC_ARMPLL_PFD1] = CLOCK_SRC_ARMPLL_PFD1_UNGATED,
    [CLOCK_SRC_ARMPLL_PFD2_UNGATED] = CLOCK_SRC_ARMPLL_VCO,
    [CLOCK_SRC_ARMPLL_PFD2] = CLOCK_SRC_ARMPLL_PFD2_UNGATED,
    [CLOCK_SRC_ARMPLL_PFD3_UNGATED] = CLOCK_SRC_ARMPLL_VCO,
    [CLOCK_SRC_ARMPLL_PFD3] = CLOCK_SRC_ARMPLL_PFD3_UNGATED,
    [CLOCK_SRC_DRAMPLL] = CLOCK_SRC_DRAMPLL_VCO,
    [CLOCK_SRC_HSIOPLL] = CLOCK_SRC_HSIOPLL_VCO,
    [CLOCK_SRC_LDBPLL] = CLOCK_SRC_LDBPLL_VCO
};

const uint8_t g_clockRootMux[CLOCK_NUM_ROOT][CLOCK_NUM_ROOT_MUX_SEL] =
{
    [CLOCK_ROOT_ADC][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ADC][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ADC][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ADC][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_TMU][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TMU][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_TMU][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_TMU][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUSAON][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUSAON][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUSAON][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUSAON][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_I3C1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_I3C1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_I3C1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_I3C1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_I3C1SLOW][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_I3C1SLOW][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_I3C1SLOW][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_I3C1SLOW][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPTMR1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPTMR1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPTMR1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPTMR1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M33][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M33][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_M33][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M33][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M33SYSTICK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M33SYSTICK][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_M33SYSTICK][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M33SYSTICK][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MQS1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MQS1][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_MQS1][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_MQS1][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_PDM][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_PDM][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_PDM][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_PDM][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SAI1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI1][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI1][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI1][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SENTINEL][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SENTINEL][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_SENTINEL][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_SENTINEL][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_TPM2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM2][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM2][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_TSTMR1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TSTMR1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_TSTMR1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_TSTMR1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAMAPB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAMAPB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAMAPB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAMAPB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAMAXI][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAMAXI][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CAMAXI][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_CAMAXI][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_CAMCM0][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAMCM0][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CAMCM0][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_CAMCM0][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_CAMISI][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAMISI][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CAMISI][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_CAMISI][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_MIPIPHYCFG][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MIPIPHYCFG][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_MIPIPHYCFG][2] = CLOCK_SRC_VIDEOPLL1,
    [CLOCK_ROOT_MIPIPHYCFG][3] = CLOCK_SRC_VIDEOPLL1,

    [CLOCK_ROOT_MIPIPHYPLLBYPASS][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MIPIPHYPLLBYPASS][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_MIPIPHYPLLBYPASS][2] = CLOCK_SRC_VIDEOPLL1,
    [CLOCK_ROOT_MIPIPHYPLLBYPASS][3] = CLOCK_SRC_VIDEOPLL1,

    [CLOCK_ROOT_MIPIPHYPLLREF][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MIPIPHYPLLREF][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_MIPIPHYPLLREF][2] = CLOCK_SRC_VIDEOPLL1,
    [CLOCK_ROOT_MIPIPHYPLLREF][3] = CLOCK_SRC_VIDEOPLL1,

    [CLOCK_ROOT_MIPITESTBYTE][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MIPITESTBYTE][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_MIPITESTBYTE][2] = CLOCK_SRC_VIDEOPLL1,
    [CLOCK_ROOT_MIPITESTBYTE][3] = CLOCK_SRC_VIDEOPLL1,

    [CLOCK_ROOT_A55][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_A55][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_A55][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_A55][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_A55MTRBUS][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_A55MTRBUS][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_A55MTRBUS][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_A55MTRBUS][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_A55PERIPH][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_A55PERIPH][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_A55PERIPH][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_A55PERIPH][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DRAMALT][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DRAMALT][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_DRAMALT][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_DRAMALT][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DRAMAPB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DRAMAPB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_DRAMAPB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_DRAMAPB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_DISPAPB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISPAPB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_DISPAPB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_DISPAPB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_DISPAXI][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISPAXI][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_DISPAXI][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_DISPAXI][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DISPOCRAM][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISPOCRAM][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_DISPOCRAM][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_DISPOCRAM][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DISP1PIX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISP1PIX][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_DISP1PIX][2] = CLOCK_SRC_VIDEOPLL1,
    [CLOCK_ROOT_DISP1PIX][3] = CLOCK_SRC_VIDEOPLL1,

    [CLOCK_ROOT_DISP2PIX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISP2PIX][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_DISP2PIX][2] = CLOCK_SRC_RESERVED21,
    [CLOCK_ROOT_DISP2PIX][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_DISP3PIX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_DISP3PIX][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_DISP3PIX][2] = CLOCK_SRC_RESERVED23,
    [CLOCK_ROOT_DISP3PIX][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_GPUAPB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_GPUAPB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_GPUAPB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_GPUAPB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_GPU][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_GPU][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_GPU][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_GPU][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIOACSCAN480M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOACSCAN480M][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_HSIOACSCAN480M][2] = CLOCK_SRC_VIDEOPLL1,
    [CLOCK_ROOT_HSIOACSCAN480M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIOACSCAN80M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOACSCAN80M][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HSIOACSCAN80M][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HSIOACSCAN80M][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_HSIO][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIO][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIO][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIO][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIOPCIEAUX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOPCIEAUX][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HSIOPCIEAUX][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HSIOPCIEAUX][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_HSIOPCIETEST160M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOPCIETEST160M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIOPCIETEST160M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIOPCIETEST160M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIOPCIETEST400M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOPCIETEST400M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIOPCIETEST400M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIOPCIETEST400M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIOPCIETEST500M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOPCIETEST500M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_HSIOPCIETEST500M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_HSIOPCIETEST500M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_HSIOUSBTEST50M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOUSBTEST50M][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HSIOUSBTEST50M][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HSIOUSBTEST50M][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_HSIOUSBTEST60M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_HSIOUSBTEST60M][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_HSIOUSBTEST60M][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_HSIOUSBTEST60M][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUSM7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUSM7][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUSM7][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUSM7][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_M7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M7][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_M7][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_M7][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_M7SYSTICK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_M7SYSTICK][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_M7SYSTICK][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_M7SYSTICK][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUSNETCMIX][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUSNETCMIX][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUSNETCMIX][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUSNETCMIX][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENET][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENET][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENET][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_ENET][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_ENETPHYTEST200M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENETPHYTEST200M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENETPHYTEST200M][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENETPHYTEST200M][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENETPHYTEST500M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENETPHYTEST500M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENETPHYTEST500M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_ENETPHYTEST500M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_ENETPHYTEST667M][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENETPHYTEST667M][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENETPHYTEST667M][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_ENETPHYTEST667M][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_ENETREF][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENETREF][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_ENETREF][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENETREF][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_ENETTIMER1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_ENETTIMER1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_ENETTIMER1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_ENETTIMER1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_MQS2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_MQS2][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_MQS2][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_MQS2][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SAI2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI2][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI2][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI2][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_NOCAPB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NOCAPB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_NOCAPB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_NOCAPB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_NOC][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NOC][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_NOC][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_NOC][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_NPUAPB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NPUAPB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_NPUAPB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_NPUAPB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_NPU][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_NPU][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_NPU][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_NPU][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_CCMCKO1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCMCKO1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CCMCKO1][2] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_CCMCKO1][3] = CLOCK_SRC_AUDIOPLL1,

    [CLOCK_ROOT_CCMCKO2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCMCKO2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CCMCKO2][2] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_CCMCKO2][3] = CLOCK_SRC_VIDEOPLL1,

    [CLOCK_ROOT_CCMCKO3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCMCKO3][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CCMCKO3][2] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_CCMCKO3][3] = CLOCK_SRC_AUDIOPLL2,

    [CLOCK_ROOT_CCMCKO4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CCMCKO4][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_CCMCKO4][2] = CLOCK_SRC_OSC32K,
    [CLOCK_ROOT_CCMCKO4][3] = CLOCK_SRC_VIDEOPLL1,

    [CLOCK_ROOT_VPUAPB][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_VPUAPB][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_VPUAPB][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_VPUAPB][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_VPU][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_VPU][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_VPU][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_VPU][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_VPUDSP][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_VPUDSP][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_VPUDSP][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_VPUDSP][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_VPUJPEG][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_VPUJPEG][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_VPUJPEG][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_VPUJPEG][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_AUDIOXCVR][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_AUDIOXCVR][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_AUDIOXCVR][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_AUDIOXCVR][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_BUSWAKEUP][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_BUSWAKEUP][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_BUSWAKEUP][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_BUSWAKEUP][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_CAN5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_CAN5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_CAN5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_CAN5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_FLEXIO1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_FLEXIO1][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_FLEXIO1][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_FLEXIO1][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_FLEXIO2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_FLEXIO2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_FLEXIO2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_FLEXIO2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_FLEXSPI1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_FLEXSPI1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_FLEXSPI1][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_FLEXSPI1][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_I3C2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_I3C2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_I3C2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_I3C2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_I3C2SLOW][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_I3C2SLOW][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_I3C2SLOW][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_I3C2SLOW][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C6][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C6][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C6][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C7][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C7][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C7][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPI2C8][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPI2C8][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPI2C8][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPI2C8][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI6][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI6][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI6][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI7][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI7][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI7][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPSPI8][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPSPI8][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPSPI8][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPSPI8][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPTMR2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPTMR2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPTMR2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPTMR2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART3][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART3][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART3][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART4][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART4][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART4][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART5][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART5][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART5][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART6][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART6][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART6][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART7][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART7][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART7][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART7][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_LPUART8][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_LPUART8][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_LPUART8][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_LPUART8][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_SAI3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI3][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI3][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI3][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SAI4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI4][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI4][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI4][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SAI5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SAI5][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SAI5][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SAI5][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SPDIF][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SPDIF][1] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_SPDIF][2] = CLOCK_SRC_AUDIOPLL2,
    [CLOCK_ROOT_SPDIF][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_SWOTRACE][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_SWOTRACE][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_SWOTRACE][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_SWOTRACE][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_TPM4][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM4][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM4][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM4][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_TPM5][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM5][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM5][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM5][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_TPM6][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TPM6][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_TPM6][2] = CLOCK_SRC_AUDIOPLL1,
    [CLOCK_ROOT_TPM6][3] = CLOCK_SRC_EXT,

    [CLOCK_ROOT_TSTMR2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_TSTMR2][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_TSTMR2][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_TSTMR2][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_USBPHYBURUNIN][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USBPHYBURUNIN][1] = CLOCK_SRC_SYSPLL1_PFD0_DIV2,
    [CLOCK_ROOT_USBPHYBURUNIN][2] = CLOCK_SRC_SYSPLL1_PFD1_DIV2,
    [CLOCK_ROOT_USBPHYBURUNIN][3] = CLOCK_SRC_FRO,

    [CLOCK_ROOT_USDHC1][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USDHC1][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_USDHC1][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_USDHC1][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_USDHC2][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USDHC2][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_USDHC2][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_USDHC2][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_USDHC3][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_USDHC3][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_USDHC3][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_USDHC3][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_V2XPK][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_V2XPK][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_V2XPK][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_V2XPK][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_WAKEUPAXI][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_WAKEUPAXI][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_WAKEUPAXI][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_WAKEUPAXI][3] = CLOCK_SRC_SYSPLL1_PFD2,

    [CLOCK_ROOT_XSPISLVROOT][0] = CLOCK_SRC_OSC24M,
    [CLOCK_ROOT_XSPISLVROOT][1] = CLOCK_SRC_SYSPLL1_PFD0,
    [CLOCK_ROOT_XSPISLVROOT][2] = CLOCK_SRC_SYSPLL1_PFD1,
    [CLOCK_ROOT_XSPISLVROOT][3] = CLOCK_SRC_SYSPLL1_PFD2
};

/* CCM GPR-selected clocks may be sources/roots.  Encode selections
 * that map to roots as offset from CLOCK_NUM_SRC for unique mapping.
 */
const ccm_gpr_sel_attr_t g_clockGprSel[CLOCK_NUM_GPR_SEL] =
{
    [CLOCK_GPR_SEL_EXT]
    {
        .selIdx = 0U,
        .selMask = 0x1U,
        .selShift = 0U,
        .selMux[0] = CLOCK_SRC_EXT1,
        .selMux[1] = CLOCK_SRC_EXT2,
    },
    /* EXT2/EXT3/EXT4 all tied to GND */

    [CLOCK_GPR_SEL_A55C0]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE0_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE0_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD0,
    },

    [CLOCK_GPR_SEL_A55C1]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE1_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE1_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD0,
    },

    [CLOCK_GPR_SEL_A55C2]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE2_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE2_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD1,
    },

    [CLOCK_GPR_SEL_A55C3]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE3_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE3_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD1,
    },

    [CLOCK_GPR_SEL_A55C4]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE4_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE4_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD2,
    },

    [CLOCK_GPR_SEL_A55C5]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_CORE5_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_CORE5_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD2,
    },

    [CLOCK_GPR_SEL_A55P]
    {
        .selIdx = 1U,
        .selMask = CCM_GPR_SHARED1_CA55_PLATFORM_CLOCK_SELECT_MASK,
        .selShift = CCM_GPR_SHARED1_CA55_PLATFORM_CLOCK_SELECT_SHIFT,
        .selMux[0] = CLOCK_NUM_SRC + CLOCK_ROOT_A55,
        .selMux[1] = CLOCK_SRC_ARMPLL_PFD3,
    },

    [CLOCK_GPR_SEL_DRAM]
    {
        .selIdx = 2U,
        .selMask = CCM_GPR_SHARED2_DRAM_PLL_BYPASS_MASK,
        .selShift = CCM_GPR_SHARED2_DRAM_PLL_BYPASS_SHIFT,
        .selMux[0] = CLOCK_SRC_DRAMPLL,
        .selMux[1] = CLOCK_NUM_SRC + CLOCK_ROOT_DRAMALT,
    },

    [CLOCK_GPR_SEL_TEMPSENSE]
    {
        .selIdx = 2U,
        .selMask = CCM_GPR_SHARED2_ANAMIX_TEMPSENSE_CLK_SEL_MASK,
        .selShift = CCM_GPR_SHARED2_ANAMIX_TEMPSENSE_CLK_SEL_SHIFT,
        .selMux[0] = CLOCK_SRC_OSC24M,
        .selMux[1] = CLOCK_SRC_FRO,
    }
};

/* CCM CGC attributes */
const ccm_cgc_attr_t g_clockCgcAttr[CLOCK_NUM_CGC] =
{
    [CLOCK_CGC_GPU]
    {
        .lpcgIdx = 24U,
        .rootIdx = CLOCK_ROOT_GPU,
    }
};

/*--------------------------------------------------------------------------*/
/* Check if CCM clock source power domain enabled                           */
/*--------------------------------------------------------------------------*/
static bool CLOCK_SourcePdIsOn(uint32_t sourceIdx)
{
    bool pdOn = true;

    switch(sourceIdx)
    {
        case CLOCK_SRC_ARMPLL_VCO:
        case CLOCK_SRC_ARMPLL_PFD0:
        case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
        case CLOCK_SRC_ARMPLL_PFD1:
        case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
        case CLOCK_SRC_ARMPLL_PFD2:
        case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
        case CLOCK_SRC_ARMPLL_PFD3:
        case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_A55P);
            break;

        case CLOCK_SRC_DRAMPLL_VCO:
        case CLOCK_SRC_DRAMPLL:
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_DDR);
            break;

        case CLOCK_SRC_HSIOPLL_VCO:
        case CLOCK_SRC_HSIOPLL:
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_HSIO_TOP);
            break;

        case CLOCK_SRC_LDBPLL_VCO:
        case CLOCK_SRC_LDBPLL:
            pdOn = SRC_MixIsPwrReady(PWR_MIX_SLICE_IDX_DISPLAY);
            break;

        default:
            ; /* Intentional empty default */
            break;
    }

    return pdOn;
}

/*--------------------------------------------------------------------------*/
/* Get CCM clock source enable status                                       */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceGetEnable(uint32_t sourceIdx)
{
    bool clkEnable = false;
    
    if (CLOCK_SourcePdIsOn(sourceIdx))
    {
        switch(sourceIdx)
        {
            case CLOCK_SRC_EXT:
                clkEnable = true;
                break;

            case CLOCK_SRC_OSC32K:
                clkEnable = true;
                break;

            case CLOCK_SRC_OSC24M:
                clkEnable = true;
                break;

            case CLOCK_SRC_FRO:
                clkEnable = true;
                break;

            case CLOCK_SRC_SYSPLL1_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_SYS1,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_DIV2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;
            
            case CLOCK_SRC_SYSPLL1_PFD1:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_DIV2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 1,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;
            
            case CLOCK_SRC_SYSPLL1_PFD2_DIV2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_VIDEOPLL1_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_VIDEO1,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_VIDEOPLL1:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_VIDEO1,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_ARM,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD0:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD1:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD2:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_ENABLE_MASK);
                break;

            case CLOCK_SRC_ARMPLL_PFD3:
                clkEnable = FRACTPLL_GetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_DRAMPLL:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_HSIOPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_HSIOPLL:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_LDBPLL_VCO:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_POWERUP_MASK);
                break;

            case CLOCK_SRC_LDBPLL:
                clkEnable = FRACTPLL_GetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_CLKMUX_EN_MASK);
                break;

            case CLOCK_SRC_EXT1:
                clkEnable = true;
                break;

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return clkEnable;
}

/*--------------------------------------------------------------------------*/
/* Set CCM clock source enable                                              */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceSetEnable(uint32_t sourceIdx, bool enable)
{
    bool updateEnable = false;

    if (CLOCK_SourcePdIsOn(sourceIdx))
    {
        switch(sourceIdx)
        {
            case CLOCK_SRC_OSC32K:
                updateEnable = true;
                break;

            case CLOCK_SRC_OSC24M:
                updateEnable = true;
                break;

            case CLOCK_SRC_SYSPLL1_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_SYS1,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_DIV2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 0U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_DIV2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 1U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_DIV2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_SYS1, 2U,
                    PLL_NO_OF_DFS_CLKOUT_DIVBY2_EN_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO1,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_AUDIO2,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_VIDEOPLL1_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_VIDEO1,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_VIDEOPLL1:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_VIDEO1,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_ARM,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD0:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 0U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD1:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 1U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD2:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 2U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_ENABLE_MASK, enable);
                break;

            case CLOCK_SRC_ARMPLL_PFD3:
                updateEnable = FRACTPLL_SetDfsEnable(CLOCK_PLL_ARM, 3U,
                    PLL_NO_OF_DFS_CLKOUT_EN_MASK, enable);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_DRAMPLL:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_DRAM,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_HSIOPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_HSIOPLL:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_HSIO,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            case CLOCK_SRC_LDBPLL_VCO:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_POWERUP_MASK, enable);
                break;

            case CLOCK_SRC_LDBPLL:
                updateEnable = FRACTPLL_SetEnable(CLOCK_PLL_LDB,
                    PLL_CTRL_CLKMUX_EN_MASK, enable);
                break;

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return updateEnable;
}

/*--------------------------------------------------------------------------*/
/* Get CCM clock source rate                                                */
/*--------------------------------------------------------------------------*/
uint64_t CLOCK_SourceGetRate(uint32_t sourceIdx)
{
    uint64_t rate = 0UL;

    if (CLOCK_SourcePdIsOn(sourceIdx))
    {        
        switch(sourceIdx)
        {
            case CLOCK_SRC_EXT:
                /* Refrain from calling CLOCK_GprSelGetRate to avoid
                   possible recursion */
                rate = CCM_GprSelExtGetRate();
                break;

            case CLOCK_SRC_OSC32K:
                rate = CLOCK_OSC32K_HZ;
                break;

            case CLOCK_SRC_OSC24M:
                rate = CLOCK_OSC24M_HZ;
                break;

            case CLOCK_SRC_FRO:
                {
                    uint32_t froRate;
                    
                    if (FRO_GetRate(&froRate))
                    {
                        rate = ((uint64_t) froRate) * CLOCK_M_HZ;
                    }
                    else
                    {
                        rate = CLOCK_FRO_HZ;
                    }
                }
                break;

            case CLOCK_SRC_SYSPLL1_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_SYS1, true);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
            case CLOCK_SRC_SYSPLL1_PFD0:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 0U, false);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_DIV2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 0U, true);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
            case CLOCK_SRC_SYSPLL1_PFD1:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 1U, false);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_DIV2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 1U, true);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
            case CLOCK_SRC_SYSPLL1_PFD2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 2U, false);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_DIV2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_SYS1, 2U, true);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO1, true);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO1, false);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO2, true);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                rate = FRACTPLL_GetRate(CLOCK_PLL_AUDIO2, false);
                break;

            case CLOCK_SRC_VIDEOPLL1_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_VIDEO1, true);
                break;

            case CLOCK_SRC_VIDEOPLL1:
                rate = FRACTPLL_GetRate(CLOCK_PLL_VIDEO1, false);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_ARM, true);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD0:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 0U, false);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD1:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 1U, false);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD2:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 2U, false);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
            case CLOCK_SRC_ARMPLL_PFD3:
                rate = FRACTPLL_GetDfsRate(CLOCK_PLL_ARM, 3U, false);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_DRAM, true);
                break;

            case CLOCK_SRC_DRAMPLL:
                rate = FRACTPLL_GetRate(CLOCK_PLL_DRAM, false);
                break;

            case CLOCK_SRC_HSIOPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_HSIO, true);
                break;

            case CLOCK_SRC_HSIOPLL:
                rate = FRACTPLL_GetRate(CLOCK_PLL_HSIO, false);
                break;

            case CLOCK_SRC_LDBPLL_VCO:
                rate = FRACTPLL_GetRate(CLOCK_PLL_LDB, true);
                break;

            case CLOCK_SRC_LDBPLL:
                rate = FRACTPLL_GetRate(CLOCK_PLL_LDB, false);
                break;

            case CLOCK_SRC_EXT1:
                /* EXT1 is board-specific.  Return rate stored on
                 * previous set rate call for this source.
                 */
                rate = g_clockExt1Rate;
                break;

                /* EXT2 internally tied to GND, no case needed */

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return rate;
}

/*--------------------------------------------------------------------------*/
/* Set CCM clock source rate                                                */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceSetRate(uint32_t sourceIdx, uint64_t rate,
    uint32_t roundRule)
{
    bool updateRate = false;

    if (CLOCK_SourcePdIsOn(sourceIdx))
    {
        switch(sourceIdx)
        {
            case CLOCK_SRC_SYSPLL1_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_SYS1, true, rate);
                break;

            case CLOCK_SRC_SYSPLL1_PFD0_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_SYS1, 0U, rate);
                break;

            case CLOCK_SRC_SYSPLL1_PFD1_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_SYS1, 1U, rate);
                break;

            case CLOCK_SRC_SYSPLL1_PFD2_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_SYS1, 2U, rate);
                break;

            case CLOCK_SRC_AUDIOPLL1_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO1, true, rate);
                break;

            case CLOCK_SRC_AUDIOPLL1:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO1, false, rate);
                break;

            case CLOCK_SRC_AUDIOPLL2_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO2, true, rate);
                break;

            case CLOCK_SRC_AUDIOPLL2:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_AUDIO2, false, rate);
                break;

            case CLOCK_SRC_VIDEOPLL1_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_VIDEO1, true, rate);
                break;

            case CLOCK_SRC_VIDEOPLL1:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_VIDEO1, false, rate);
                break;

            case CLOCK_SRC_ARMPLL_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_ARM, true, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD0_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 0U, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD1_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 1U, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD2_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 2U, rate);
                break;

            case CLOCK_SRC_ARMPLL_PFD3_UNGATED:
                updateRate = FRACTPLL_SetDfsRate(CLOCK_PLL_ARM, 3U, rate);
                break;

            case CLOCK_SRC_DRAMPLL_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_DRAM, true, rate);
                break;

            case CLOCK_SRC_DRAMPLL:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_DRAM, false, rate);
                break;

            case CLOCK_SRC_HSIOPLL_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_HSIO, true, rate);
                break;

            case CLOCK_SRC_HSIOPLL:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_HSIO, false, rate);
                break;

            case CLOCK_SRC_LDBPLL_VCO:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_LDB, true, rate);
                break;

            case CLOCK_SRC_LDBPLL:
                updateRate = FRACTPLL_SetRate(CLOCK_PLL_LDB, false, rate);
                break;

            case CLOCK_SRC_EXT1:
                /* EXT1 is board-specific.  Store the rate to be
                 * used on subsequent get rate calls for this source.
                 */
                g_clockExt1Rate = rate;
                updateRate = true;
                break;

            default:
                ; /* Intentional empty default */
                break;
        }
    }

    return updateRate;
}

/*--------------------------------------------------------------------------*/
/* Get parent for CCM clock source                                          */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceGetParent(uint32_t sourceIdx, uint32_t *parentIdx)
{
    bool rc = false;

    if (sourceIdx < CLOCK_NUM_SRC)
    {
        if (s_clockSourceNumInputs[sourceIdx] != 0U)
        {
            *parentIdx = s_clockSourceParent[sourceIdx];
            rc = true;
        }
    }

    return rc;
}

/*--------------------------------------------------------------------------*/
/* Set parent for CCM clock source                                          */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceSetParent(uint32_t sourceIdx, uint32_t parentIdx)
{
    bool rc = false;

    if (sourceIdx < CLOCK_NUM_SRC)
    {
        if (s_clockSourceNumInputs[sourceIdx] != 0U)
        {
            /* Requested parent must match clock source input */
            rc = (parentIdx == s_clockSourceParent[sourceIdx]);
        }
    }

    return rc;
}

/*--------------------------------------------------------------------------*/
/* Set CCM clock source spread spectrum                                     */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceSetSsc(uint32_t sourceIdx, uint32_t spreadPercent,
    uint32_t modFreq, uint32_t enable)
{
    bool setSscConfig = false;

    switch (sourceIdx)
    {
        case CLOCK_SRC_SYSPLL1_VCO:
            /* PLL SYS */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_SYS1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL1_VCO:
            /* PLL AUDIO1 */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_AUDIO1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL2_VCO:
            /* PLL AUDIO2 */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_AUDIO2,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_VIDEOPLL1_VCO:
            /* PLL VIDEO1 */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_VIDEO1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_DRAMPLL_VCO:
            /* PLL DRAM */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_DRAM,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_HSIOPLL_VCO:
            /* PLL HSIO */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_HSIO,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_LDBPLL_VCO:
            /* PLL LDB */
            setSscConfig = FRACTPLL_SetSscConfig(CLOCK_PLL_LDB,
                spreadPercent, modFreq, enable);
            break;

        default:
            ; /* Intentional empty default */
            break;
    }

    return setSscConfig;
}

/*--------------------------------------------------------------------------*/
/* Get CCM clock source spread spectrum                                     */
/*--------------------------------------------------------------------------*/
bool CLOCK_SourceGetSsc(uint32_t sourceIdx, uint32_t *spreadPercent,
    uint32_t *modFreq, uint32_t *enable)
{
    bool getSscConfig = false;

    switch (sourceIdx)
    {
        case CLOCK_SRC_SYSPLL1_VCO:
            /* PLL SYS */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_SYS1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL1_VCO:
            /* PLL AUDIO1 */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_AUDIO1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_AUDIOPLL2_VCO:
            /* PLL AUDIO2 */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_AUDIO2,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_VIDEOPLL1_VCO:
            /* PLL VIDEO */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_VIDEO1,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_DRAMPLL_VCO:
            /* PLL DRAM */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_DRAM,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_HSIOPLL_VCO:
            /* PLL HSIO */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_HSIO,
                spreadPercent, modFreq, enable);
            break;

        case CLOCK_SRC_LDBPLL_VCO:
            /* PLL LDB */
            getSscConfig = FRACTPLL_GetSscConfig(CLOCK_PLL_LDB,
                spreadPercent, modFreq, enable);
            break;

        default:
            ; /* Intentional empty default */
            break;
    }

    return getSscConfig;
}

