/*
** ###################################################################
**     Processors:          MIMX95_cm33
**
**
**     Abstract:
**         CMSIS Peripheral Access Layer for MIMX95_cm33
**
**     Copyright 1997-2016 Freescale Semiconductor, Inc.
**     Copyright 2016-2023 NXP
**     All rights reserved.
**
**     SPDX-License-Identifier: BSD-3-Clause
**
**     http:                 www.nxp.com
**     mail:                 support@nxp.com
**
**     Revisions:
**
** ###################################################################
*/

/*!
 * @file MIMX95_BLK_CTRL_NOCMIX.h
 * @version 0.0
 * @date 0-00-00
 * @brief CMSIS Peripheral Access Layer for MIMX95_BLK_CTRL_NOCMIX
 *
 * CMSIS Peripheral Access Layer for MIMX95
 */

/* Prevention from multiple including the same memory map */
#if !defined(MIMX95_BLK_CTRL_NOCMIX_H_)  /* Check if memory map has not been already included */
#define MIMX95_BLK_CTRL_NOCMIX_H_

#include "MIMX95_COMMON.h"

/* ----------------------------------------------------------------------------
   -- BLK_CTRL_NOCMIX Peripheral Access Layer
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup BLK_CTRL_NOCMIX_Peripheral_Access_Layer BLK_CTRL_NOCMIX Peripheral Access Layer
 * @{
 */

/** BLK_CTRL_NOCMIX - Register Layout Typedef */
typedef struct {
  __IO uint32_t DEXSC_ERR;                         /**< DEXSC error response configuration, offset: 0x0 */
       uint8_t RESERVED_0[4];
  __IO uint32_t AXI_LIMIT_WAKEUPMIX;               /**< AXI limit wakeupmix configuration, offset: 0x8 */
  __IO uint32_t CACHE_ATTR;                        /**< AxCACHE[1] override configuration register, offset: 0xC */
       uint8_t RESERVED_1[20];
  __IO uint32_t TIE_VALUE;                         /**< GPR for uncertain tie0 or tie1, offset: 0x24 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_0;          /**< AXI beat limiter 0 configuration, offset: 0x28 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_1;          /**< AXI beat limiter 1 configuration, offset: 0x2C */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_2;          /**< AXI beat limiter 2 configuration, offset: 0x30 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_3;          /**< AXI beat limiter 3 configuration, offset: 0x34 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_4;          /**< AXI beat limiter 4 configuration, offset: 0x38 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_5;          /**< AXI beat limiter 5 configuration, offset: 0x3C */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_6;          /**< AXI beat limiter 6 configuration, offset: 0x40 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_7;          /**< AXI beat limiter 7 configuration, offset: 0x44 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_8;          /**< AXI beat limiter 8 configuration, offset: 0x48 */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_9;          /**< AXI beat limiter 9 configuration, offset: 0x4C */
  __IO uint32_t AXI_LIMIT_BEAT_LIMITER_10;         /**< AXI beat limiter 10 configuration, offset: 0x50 */
  __IO uint32_t WAKEUPMIX_PRESSURE_HURRY;          /**< WAKEUPMIX pressure/hurry value configuration, offset: 0x54 */
  __IO uint32_t VPUMIX_PRESSURE_HURRY;             /**< VPUMIX pressure/hurry value configuration, offset: 0x58 */
  __IO uint32_t HSIOMIX_PRESSURE_HURRY;            /**< HSIOMUX pressure/hurry value configuration, offset: 0x5C */
  __IO uint32_t MMU700_PRESSURE_HURRY;             /**< MMU700 pressure/hurry value configuration, offset: 0x60 */
  __IO uint32_t NETCMIX_PRESSURE_HURRY;            /**< NETCMIX pressure/hurry value configuration, offset: 0x64 */
  __IO uint32_t DISPLAYMIX_RT_PRESSURE_HURRY;      /**< DISPLAYMIX_RT pressure/hurry value configuration, offset: 0x68 */
  __IO uint32_t GPUMIX_PRESSURE_HURRY;             /**< GPUMIX pressure/hurry value configuration, offset: 0x6C */
  __IO uint32_t NPUMIX_PRESSURE_HURRY;             /**< NPUMIX pressure/hurry value configuration, offset: 0x70 */
  __IO uint32_t GIC700_PRESSURE_HURRY;             /**< GIC700 pressure/hurry value configuration, offset: 0x74 */
  __IO uint32_t CORTEXAMIX_B_PRESSURE_HURRY;       /**< CORTEXAMIX B pressure/hurry value configuration, offset: 0x78 */
  __IO uint32_t CORTEXAMIX_A_PRESSURE_HURRY;       /**< CORTEXAMIX A pressure/hurry value configuration, offset: 0x7C */
  __IO uint32_t OCRAM_SGLECC_ERR_INT;              /**< OCRAM single ECC error interrupt flag, offset: 0x80 */
       uint8_t RESERVED_2[60];
  __IO uint32_t NIU_TO_CTRL_WAKEUP;                /**< WAKEUPMIX NIU Timeout Control Register, offset: 0xC0 */
  __IO uint32_t NIU_TO_CTRL_CORTEXA;               /**< CORTEXAMIX NIU Timeout Control Register, offset: 0xC4 */
  __IO uint32_t NIU_TO_CTRL_GIC700;                /**< GIC700 NIU Timeout Control Register, offset: 0xC8 */
  __IO uint32_t NIU_TO_CTRL_NPU;                   /**< NPUMIX NIU Timeout Control Register, offset: 0xCC */
  __IO uint32_t NIU_TO_CTRL_GPU;                   /**< GPUMIX NIU Timeout Control Register, offset: 0xD0 */
  __IO uint32_t NIU_TO_CTRL_CAMERA;                /**< CAMERAMIX NIU Timeout Control Register, offset: 0xD4 */
  __IO uint32_t NIU_TO_CTRL_DISPLAY_RT;            /**< DISPLAYMIX (real time) NIU Timeout Control Register, offset: 0xD8 */
  __IO uint32_t NIU_TO_CTRL_NETC;                  /**< NETCMIX NIU Timeout Control Register, offset: 0xDC */
  __IO uint32_t NIU_TO_CTRL_MMU700;                /**< MMU700 NIU Timeout Control Register, offset: 0xE0 */
  __IO uint32_t NIU_TO_CTRL_HSIO;                  /**< HSIOMIX NIU Timeout Control Register, offset: 0xE4 */
  __IO uint32_t NIU_TO_CTRL_DISPLAY_BE;            /**< DISPLAYMIX (best effort) NIU Timeout Control Register, offset: 0xE8 */
  __IO uint32_t NIU_TO_CTRL_VPU;                   /**< VPUMIX NIU Timeout Control Register, offset: 0xEC */
} BLK_CTRL_NOCMIX_Type;

/* ----------------------------------------------------------------------------
   -- BLK_CTRL_NOCMIX Register Masks
   ---------------------------------------------------------------------------- */

/*!
 * @addtogroup BLK_CTRL_NOCMIX_Register_Masks BLK_CTRL_NOCMIX Register Masks
 * @{
 */

/*! @name DEXSC_ERR - DEXSC error response configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_ERR_RESP_EN_MASK (0x1U)
#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_ERR_RESP_EN_SHIFT (0U)
/*! NPU_ERR_RESP_EN - NPU RAM error response enable */
#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_ERR_RESP_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_ERR_RESP_EN_SHIFT)) & BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_ERR_RESP_EN_MASK)

#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_EXC_ERR_RESP_EN_MASK (0x2U)
#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_EXC_ERR_RESP_EN_SHIFT (1U)
/*! NPU_EXC_ERR_RESP_EN - NPU RAM exclusive access error response enable */
#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_EXC_ERR_RESP_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_EXC_ERR_RESP_EN_SHIFT)) & BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_EXC_ERR_RESP_EN_MASK)

#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_LOCK_ERR_RESP_EN_MASK (0x4U)
#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_LOCK_ERR_RESP_EN_SHIFT (2U)
/*! NPU_LOCK_ERR_RESP_EN - NPU RAM lock error response enable */
#define BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_LOCK_ERR_RESP_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_LOCK_ERR_RESP_EN_SHIFT)) & BLK_CTRL_NOCMIX_DEXSC_ERR_NPU_LOCK_ERR_RESP_EN_MASK)
/*! @} */

/*! @name AXI_LIMIT_WAKEUPMIX - AXI limit wakeupmix configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_ENABLE_SHIFT (0U)
/*! ENABLE - Enable beat limiter */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_WAKEUPMIX_BEAT_LIMIT_MASK)
/*! @} */

/*! @name CACHE_ATTR - AxCACHE[1] override configuration register */
/*! @{ */

#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_EN_MASK (0x1U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_EN_SHIFT (0U)
/*! WAKEUPMIX_ARCACHE_EN - WAKEUPMIX ARCACHE[1] override enable */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_EN_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_EN_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_EN_MASK (0x2U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_EN_SHIFT (1U)
/*! WAKEUPMIX_AWCACHE_EN - WAKEUPMIX AWCACHE[1] override enable */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_EN_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_EN_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_EN_MASK (0x4U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_EN_SHIFT (2U)
/*! CACHE_ARCACHE_EN - CACHE ARCACHE[1] override enable */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_EN_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_EN_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_EN_MASK (0x8U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_EN_SHIFT (3U)
/*! CACHE_AWCACHE_EN - CACHE AWCACHE[1] override enable */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_EN_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_EN_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_EN_MASK (0x10U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_EN_SHIFT (4U)
/*! HSIOMIX_ARCACHE_EN - HSIOMIX ARCACHE[1] override enable */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_EN_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_EN_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_EN_MASK (0x20U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_EN_SHIFT (5U)
/*! HSIOMIX_AWCACHE_EN - HSIOMIX AWCACHE[1] override enable */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_EN(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_EN_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_EN_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_MASK (0x10000U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_SHIFT (16U)
/*! WAKEUPMIX_ARCACHE - WAKEUPMIX ARCACHE[1] override value */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_ARCACHE_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_MASK (0x20000U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_SHIFT (17U)
/*! WAKEUPMIX_AWCACHE - WAKEUPMIX AWCACHE[1] override value */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_WAKEUPMIX_AWCACHE_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_MASK (0x40000U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_SHIFT (18U)
/*! CACHE_ARCACHE - CACHE ARCACHE[1] override value */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_ARCACHE_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_MASK (0x80000U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_SHIFT (19U)
/*! CACHE_AWCACHE - CACHE AWCACHE[1] override value */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_CACHE_AWCACHE_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_MASK (0x100000U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_SHIFT (20U)
/*! HSIOMIX_ARCACHE - HSIOMIX ARCACHE[1] override value */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_ARCACHE_MASK)

#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_MASK (0x200000U)
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_SHIFT (21U)
/*! HSIOMIX_AWCACHE - HSIOMIX AWCACHE[1] override value */
#define BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_SHIFT)) & BLK_CTRL_NOCMIX_CACHE_ATTR_HSIOMIX_AWCACHE_MASK)
/*! @} */

/*! @name TIE_VALUE - GPR for uncertain tie0 or tie1 */
/*! @{ */

#define BLK_CTRL_NOCMIX_TIE_VALUE_AIPS4_HBSTRB_MASK (0xFU)
#define BLK_CTRL_NOCMIX_TIE_VALUE_AIPS4_HBSTRB_SHIFT (0U)
/*! AIPS4_HBSTRB - AIPS4_HBSTRB tie */
#define BLK_CTRL_NOCMIX_TIE_VALUE_AIPS4_HBSTRB(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_TIE_VALUE_AIPS4_HBSTRB_SHIFT)) & BLK_CTRL_NOCMIX_TIE_VALUE_AIPS4_HBSTRB_MASK)

#define BLK_CTRL_NOCMIX_TIE_VALUE_GICT_ALLOW_NS_MASK (0x40U)
#define BLK_CTRL_NOCMIX_TIE_VALUE_GICT_ALLOW_NS_SHIFT (6U)
/*! GICT_ALLOW_NS - GICT_ALLOW_NS */
#define BLK_CTRL_NOCMIX_TIE_VALUE_GICT_ALLOW_NS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_TIE_VALUE_GICT_ALLOW_NS_SHIFT)) & BLK_CTRL_NOCMIX_TIE_VALUE_GICT_ALLOW_NS_MASK)

#define BLK_CTRL_NOCMIX_TIE_VALUE_GICP_ALLOW_NS_MASK (0x80U)
#define BLK_CTRL_NOCMIX_TIE_VALUE_GICP_ALLOW_NS_SHIFT (7U)
/*! GICP_ALLOW_NS - GICP_ALLOW_NS tie */
#define BLK_CTRL_NOCMIX_TIE_VALUE_GICP_ALLOW_NS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_TIE_VALUE_GICP_ALLOW_NS_SHIFT)) & BLK_CTRL_NOCMIX_TIE_VALUE_GICP_ALLOW_NS_MASK)

#define BLK_CTRL_NOCMIX_TIE_VALUE_ARSNOOP_S_MASK (0x3C0000U)
#define BLK_CTRL_NOCMIX_TIE_VALUE_ARSNOOP_S_SHIFT (18U)
/*! ARSNOOP_S - ARSNOOP_S tie */
#define BLK_CTRL_NOCMIX_TIE_VALUE_ARSNOOP_S(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_TIE_VALUE_ARSNOOP_S_SHIFT)) & BLK_CTRL_NOCMIX_TIE_VALUE_ARSNOOP_S_MASK)

#define BLK_CTRL_NOCMIX_TIE_VALUE_AWSNOOP_S_MASK (0x3C00000U)
#define BLK_CTRL_NOCMIX_TIE_VALUE_AWSNOOP_S_SHIFT (22U)
/*! AWSNOOP_S - AWNSOOP_S tie */
#define BLK_CTRL_NOCMIX_TIE_VALUE_AWSNOOP_S(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_TIE_VALUE_AWSNOOP_S_SHIFT)) & BLK_CTRL_NOCMIX_TIE_VALUE_AWSNOOP_S_MASK)

#define BLK_CTRL_NOCMIX_TIE_VALUE_DFTRAMHOLD_MASK (0x20000000U)
#define BLK_CTRL_NOCMIX_TIE_VALUE_DFTRAMHOLD_SHIFT (29U)
/*! DFTRAMHOLD - DFTRAMHOLD tie */
#define BLK_CTRL_NOCMIX_TIE_VALUE_DFTRAMHOLD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_TIE_VALUE_DFTRAMHOLD_SHIFT)) & BLK_CTRL_NOCMIX_TIE_VALUE_DFTRAMHOLD_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_0 - AXI beat limiter 0 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 0 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_0_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_1 - AXI beat limiter 1 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 1 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_1_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_2 - AXI beat limiter 2 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 2 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_2_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_3 - AXI beat limiter 3 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 3 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_3_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_4 - AXI beat limiter 4 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 4 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_4_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_5 - AXI beat limiter 5 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 5 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_5_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_6 - AXI beat limiter 6 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 6 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_6_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_7 - AXI beat limiter 7 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 7 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_7_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_8 - AXI beat limiter 8 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 8 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_8_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_9 - AXI beat limiter 9 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 9 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_9_BEAT_LIMIT_MASK)
/*! @} */

/*! @name AXI_LIMIT_BEAT_LIMITER_10 - AXI beat limiter 10 configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_ENABLE_MASK (0x1U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_ENABLE_SHIFT (0U)
/*! ENABLE - Beat limiter 10 enable */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_ENABLE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_ENABLE_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_ENABLE_MASK)

#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_BEAT_LIMIT_MASK (0xFFFF0000U)
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_BEAT_LIMIT_SHIFT (16U)
/*! BEAT_LIMIT - Burst beat limit */
#define BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_BEAT_LIMIT(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_BEAT_LIMIT_SHIFT)) & BLK_CTRL_NOCMIX_AXI_LIMIT_BEAT_LIMITER_10_BEAT_LIMIT_MASK)
/*! @} */

/*! @name WAKEUPMIX_PRESSURE_HURRY - WAKEUPMIX pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - WAKEUPMIX hurry value */
#define BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - WAKUPMIX pressure value */
#define BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_WAKEUPMIX_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name VPUMIX_PRESSURE_HURRY - VPUMIX pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - VPUMIX pressure value */
#define BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - VPUMIX pressure value */
#define BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_VPUMIX_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name HSIOMIX_PRESSURE_HURRY - HSIOMUX pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - HSIOMIX hurry value */
#define BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - HSIOMIX pressure value */
#define BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_HSIOMIX_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name MMU700_PRESSURE_HURRY - MMU700 pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - MMU700 hurry value */
#define BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - MMU700 pressure value */
#define BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_MMU700_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name NETCMIX_PRESSURE_HURRY - NETCMIX pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - NETCMIX pressure value */
#define BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - NETCMIX pressure value */
#define BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_NETCMIX_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name DISPLAYMIX_RT_PRESSURE_HURRY - DISPLAYMIX_RT pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - DISPLAYMIX_RT hurry value */
#define BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - DISPLAYMIX_RT pressure value */
#define BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_DISPLAYMIX_RT_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name GPUMIX_PRESSURE_HURRY - GPUMIX pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - GPUMIX hurry value */
#define BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - GPUMIX pressure value */
#define BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_GPUMIX_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name NPUMIX_PRESSURE_HURRY - NPUMIX pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - NPUMIX hurry value */
#define BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - NPUMIX pressure value */
#define BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_NPUMIX_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name GIC700_PRESSURE_HURRY - GIC700 pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - GIC700 hurry value */
#define BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - GIC700 pressure value */
#define BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_GIC700_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name CORTEXAMIX_B_PRESSURE_HURRY - CORTEXAMIX B pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - CORTEXAMIX B hurry value */
#define BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - CORTEXAMIX B pressure value */
#define BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_CORTEXAMIX_B_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name CORTEXAMIX_A_PRESSURE_HURRY - CORTEXAMIX A pressure/hurry value configuration */
/*! @{ */

#define BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_HURRY_MASK (0x7U)
#define BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_HURRY_SHIFT (0U)
/*! HURRY - CORTEXAMIX A hurry value */
#define BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_HURRY(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_HURRY_SHIFT)) & BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_HURRY_MASK)

#define BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_PRESSURE_MASK (0x38U)
#define BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_PRESSURE_SHIFT (3U)
/*! PRESSURE - CORTEXAMIX A pressure value */
#define BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_PRESSURE(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_PRESSURE_SHIFT)) & BLK_CTRL_NOCMIX_CORTEXAMIX_A_PRESSURE_HURRY_PRESSURE_MASK)
/*! @} */

/*! @name OCRAM_SGLECC_ERR_INT - OCRAM single ECC error interrupt flag */
/*! @{ */

#define BLK_CTRL_NOCMIX_OCRAM_SGLECC_ERR_INT_SGL_ECC_ERR_IF_MASK (0x1U)
#define BLK_CTRL_NOCMIX_OCRAM_SGLECC_ERR_INT_SGL_ECC_ERR_IF_SHIFT (0U)
/*! SGL_ECC_ERR_IF - OCRAM single ECC error interrupt flag */
#define BLK_CTRL_NOCMIX_OCRAM_SGLECC_ERR_INT_SGL_ECC_ERR_IF(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_OCRAM_SGLECC_ERR_INT_SGL_ECC_ERR_IF_SHIFT)) & BLK_CTRL_NOCMIX_OCRAM_SGLECC_ERR_INT_SGL_ECC_ERR_IF_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_WAKEUP - WAKEUPMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_WAKEUP_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_CORTEXA - CORTEXAMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_CORTEXA_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_GIC700 - GIC700 NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_GIC700_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_NPU - NPUMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_NPU_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_GPU - GPUMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_GPU_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_CAMERA - CAMERAMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_CAMERA_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_DISPLAY_RT - DISPLAYMIX (real time) NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_RT_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_NETC - NETCMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_NETC_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_MMU700 - MMU700 NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_MMU700_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_HSIO - HSIOMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_HSIO_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_DISPLAY_BE - DISPLAYMIX (best effort) NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_DISPLAY_BE_DIS_MASK)
/*! @} */

/*! @name NIU_TO_CTRL_VPU - VPUMIX NIU Timeout Control Register */
/*! @{ */

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_CLK_DIV_RATIO_MASK (0x7U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_CLK_DIV_RATIO_SHIFT (0U)
/*! CLK_DIV_RATIO - Division ratio for external reference clock
 *  0b000..Divide by 4
 *  0b001..Divide by 8
 *  0b010..Divide by 16
 *  0b011..Divide by 32
 *  0b100..Divide by 64
 *  0b101..Divide by 128
 *  0b110..Divide by 256
 *  0b111..Divide by 512
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_CLK_DIV_RATIO(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_CLK_DIV_RATIO_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_CLK_DIV_RATIO_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_UPD_MASK (0x8000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_UPD_SHIFT (15U)
/*! UPD - Update clock division ratio */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_UPD(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_UPD_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_UPD_MASK)

#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_DIS_MASK (0x80000000U)
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_DIS_SHIFT (31U)
/*! DIS - Disable timeout
 *  0b0..Timeout feature is enabled
 *  0b1..Timeout feature is disabled
 */
#define BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_DIS(x) (((uint32_t)(((uint32_t)(x)) << BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_DIS_SHIFT)) & BLK_CTRL_NOCMIX_NIU_TO_CTRL_VPU_DIS_MASK)
/*! @} */


/*!
 * @}
 */ /* end of group BLK_CTRL_NOCMIX_Register_Masks */


/* BLK_CTRL_NOCMIX - Peripheral instance base addresses */
/** Peripheral BLK_CTRL_NOCMIX base address */
#define BLK_CTRL_NOCMIX_BASE                (0x49000000u)
/** Peripheral BLK_CTRL_NOCMIX base pointer */
#define BLK_CTRL_NOCMIX                     ((BLK_CTRL_NOCMIX_Type *)BLK_CTRL_NOCMIX_BASE)
/** Array initializer of BLK_CTRL_NOCMIX peripheral base addresses */
#define BLK_CTRL_NOCMIX_BASE_ADDRS           { BLK_CTRL_NOCMIX_BASE }
/** Array initializer of BLK_CTRL_NOCMIX peripheral base pointers */
#define BLK_CTRL_NOCMIX_BASE_PTRS            { BLK_CTRL_NOCMIX }

/*!
 * @}
 */ /* end of group BLK_CTRL_NOCMIX_Peripheral_Access_Layer */

#endif  /* #if !defined(MIMX95_BLK_CTRL_NOCMIX_H_) */
