/fancyfoot\[CE\]/ c\\\fancyfoot\[CE\]{\\fancyplain{}{\\bfseries\\scriptsize NXP - All Rights Reserved }}
/fancyfoot\[CO\]/ c\\\fancyfoot\[CO\]{\\fancyplain{}{\\bfseries\\scriptsize NXP - All Rights Reserved }}
/fancyfoot\[LE\]/ c\\\fancyfoot\[LE\]{\\fancyplain{}{}}
/fancyfoot\[LO\]/ c\\\fancyfoot\[LO\]{\\fancyplain{}{}}
/fancyfoot\[RE\]/ c\\\fancyfoot\[RE\]{\\fancyplain{}{}}
/fancyfoot\[RO\]/ c\\\fancyfoot\[RO\]{\\fancyplain{}{}}
/Generated by Doxygen/ c\{\\large NXP}\\\\